app/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from app import views

app_name = 'app'

urlpatterns = [
    path('', views.PaginationView.as_view(), name='index'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', login_required(views.LogoutView.as_view()), name='logout'),
    path('user/<int:id>/', login_required(views.UserView.as_view()), name='user'),
    path('users/', views.UsersView.as_view(), name='users'),
    path('ask/', login_required(views.AskQuestionView.as_view()), name='ask'),
    path('question/<int:id>/', views.QuestionView.as_view(), name='question'),
    path('top/', views.TopQuestionsView.as_view(), name='top'),
    path('tag/<str:name>/', views.TagQuestionsView.as_view(), name='tag')
]

askme/urls.py
from django.contrib import admin
from django.urls import path, include
from django.core.management import call_command
from app import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('', include('app.urls')),
                  path('admin/', admin.site.urls)
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

call_command('calc_cache')

templates/ask.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ block.super }}. Задать вопрос{% endblock %}
{% block content %}
    <div class="col-md-8">
        <h1 class="my-3">Задать вопрос</h1>
        <form class="form-horizontal" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="form-actions">
                <button class="btn btn-primary" type="submit">Задать вопрос</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/askOld.html
<!doctype html>
<html lang="en" class="h-100">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Sticky Footer Navbar Template · Bootstrap v5.1</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="../static/css/bootstrap.min.css">
    <link rel="stylesheet" href="../static/css/main.css">


    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="sticky-footer-navbar.css" rel="stylesheet">
</head>
<body class="d-flex flex-column h-100">

<header>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Fixed navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Link</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled">Disabled</a>
                    </li>
                </ul>
                <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
</header>

<!-- Begin page content -->
<main class="flex-shrink-0">
    <div class="container">
        <div class="row">
            <div class="col-9">
                <h2 class="mt-5">Ask question</h2>

                <form>
                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Question title</label>
                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                        <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
                    </div>
                    <div class="mb-3">
                        <label for="questionText" class="form-label">Question</label>
                        <textarea id="questionText" class="form-control" rows="10"></textarea>
                    </div>
                    <div class="mb-3">
                        <label for="questionTags" class="Tags">Tags</label>
                        <input type="text" id="questionTags" class="form-control">
                    </div>
                    <div class="mb-3 form-check">
                        <input type="checkbox" class="form-check-input" id="exampleCheck1">
                        <label class="form-check-label" for="exampleCheck1">Check me out</label>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>

            </div>
            <div class="col-3">
                <h2 class="mt-5">Tags</h2>
            </div>
        </div>

    </div>
</main>

<footer class="footer mt-auto py-3 bg-light">
    <div class="container">
        <span class="text-muted">Place sticky footer content here.</span>
    </div>
</footer>


<script src="/docs/5.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>


</body>
</html>

templates/base.html
{% load static %}
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="{% static 'bootstrap-5/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'base.css' %}" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="{% static 'favicon.png' %}" rel="shortcut icon" type="image/png">
    <meta charset="UTF-8">
    <title>askme{% block title %}{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <img alt="logo" src="{% static 'logo.jpeg' %}">
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item{% block navbar_home %}{% endblock %}">
                    <a class="nav-link" href="{% url 'app:index' %}">Главная</a>
                </li>
                <li class="nav-item{% block navbar_top %}{% endblock %}">
                    <a class="nav-link" href="{% url 'app:top' %}">Лучшие вопросы</a>
                </li>
                <li class="nav-item{% block navbar_users %}{% endblock %}">
                    <a class="nav-link" href="{% url 'app:users' %}">Пользователи</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    <div class="row">
        {% block content %}{% endblock %}
        <div class="col-md-4">
            <div class="card my-4">
                {% if request.user.is_authenticated %}
                    <div class="row card-body">
                        <div class="col-md-8">
                            <h5 class="text-center"><a href="{% url 'app:user' request.user.id %}">{{ request.user.username }}</a></h5>
                        </div>
                        <div class="col-md-4">
                            <a class="btn btn-secondary col-md-12" href="{% url 'app:logout' %}">Выйти</a>
                        </div>
                    </div>
                {% else %}
                    <h5 class="card-header"><a href="{% url 'app:login' %}">Вход</a></h5>
                    <h5 class="card-header"><a href="{% url 'app:signup' %}">Регистрация</a></h5>
                {% endif %}
            </div>
            <div class="card my-4">
                <h5 class="card-header">Поиск вопросов</h5>
                <div class="card-body">
                    <div class="input-group">
                        <input class="form-control" placeholder="Содержание..." type="text">
                        <span class="input-group-btn">
							<button class="btn btn-secondary" type="button">Найти</button>
						</span>
                    </div>
                </div>
            </div>
            <div class="card my-4">
                <a class="btn btn-secondary" href="{% url 'app:ask' %}">Задать вопрос</a>
            </div>
            <div class="card my-4">
                <h5 class="card-header">Популярные теги</h5>
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled mb-0">
                                {% for tag in top_tags %}
                                    {% if not forloop.counter|divisibleby:2 %}
                                        <li>
                                            <a href="{% url 'app:tag' tag %}">{{ tag }}</a>
                                        </li>
                                    {% endif %}
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="col-lg-6">
                            <ul class="list-unstyled mb-0">
                                {% for tag in top_tags %}
                                    {% if forloop.counter|divisibleby:2 %}
                                        <li>
                                            <a href="{% url 'app:tag' tag %}">{{ tag }}</a>
                                        </li>
                                    {% endif %}
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card my-4">
                <h5 class="card-header">Лучшие пользователи</h5>
                <div class="card-body">
                    <ul class="list-unstyled mb-0">
                        {% for user in top_users %}
                            <li>
                                <a href="{% url 'app:user' user.id %}">
                                    <img alt="avatar" class="rounded-circle avatar64" src="{{ user.get_avatar_url }}">
                                </a>
                                <a href="{% url 'app:user' user.id %}"
                                   style="text-align: center;">{{ user.username }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<footer class="py-5 bg-dark">
    <div class="container">
    </div>
</footer>
</body>
<script src="{% static 'jquery.js' %}" type="text/javascript"></script>
{% block script %}{% endblock %}
</html>

templates/index.html
{% extends 'questions.html' %}
{% block title %}{{ block.super }}. Главная страница{% endblock %}
{% block navbar_home %} active{% endblock %}
{% block content_header %}Главная страница. Вопросы{% endblock %}

templates/indexOld.html
{% extends "inc/base.html" %}
{% load static %}
{% load django_bootstrap5 %}
{% block content %}
    <h2 class="mt-5">Questions</h2>

    {% for question in questions %}
        {% include "inc/question.html" %}
    {% endfor %}
{% endblock %}

{% block side-panel %}
    <h2 class="mt-5">Tags</h2>
{% endblock side-panel %}

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block title %}{{ block.super }}. Авторизация{% endblock %}
{% block content %}
    <div class="col-md-8">
        <h1 class="my-3">Вход в аккаунт</h1>
        <form class="form-horizontal" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <div class="form-actions">
                <button class="btn btn-primary" type="submit">Войти</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/pagination.html
<ul class="pagination justify-content-center mb-4">
    {% if pagination.has_previous %}
        <li class="page-item">
            <button class="page-link"
                    onclick="paginationFormSubmit({{ pagination.previous_page_number }})">&larr; Предыдущие
            </button>
        </li>
    {% else %}
        <li class="page-item disabled">
            <button class="page-link">&larr; Предыдущие</button>
        </li>
    {% endif %}
    {% if pagination.has_next %}
        <li class="page-item">
            <button class="page-link"
                    onclick="paginationFormSubmit({{ pagination.next_page_number }})">Следующие &rarr;
            </button>
        </li>
    {% else %}
        <li class="page-item disabled">
            <button class="page-link">Следующие &rarr;</button>
        </li>
    {% endif %}
</ul>

templates/question.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block title %}{{ block.super }}. Вопрос{% endblock %}
{% block content %}
    <div class="col-md-8">
        <h3 class="mt-3">{{ question.title }}</h3>
        <p class="mt-0 mb-2">{{ question.text }}</p>
        <i class="mt-0 mb-0 text-secondary">
            {% for question_tag in question.tags.all %}
                &nbsp;#{{ question_tag }}
            {% endfor %}
        </i>
        <hr>
        <p class="mt-3 mb-3">
            Задан {{ question.pub_date }} пользователем
            <a href="{% url 'app:user' question.author.id %}">{{ question.author }}</a>
            <a href="{% url 'app:user' question.author.id %}">
                <img alt="Аватар пользователя" class="ml-2 rounded-circle avatar32"
                     src="{{ question.author.get_avatar_url }}">
            </a>
            <span class="fa fa-thumbs-down" id="question_rating_picture_dislike" style="margin-right: 10px;"></span>
            <span class="fa fa-thumbs-up" id="question_rating_picture_like" style="margin-right: 10px;"></span>
            <span style="cursor: default; float: right; margin-right: 10px;">
      {% if question.rating > 0 %}
          <b class="text-success" id="question_rating">{{ question.rating }}</b>
      {% elif question.rating < 0 %}
          <b class="text-danger" id="question_rating">{{ question.rating }}</b>
      {% else %}
          <b id="question_rating">{{ question.rating }}</b>
      {% endif %}
    </span>
        </p>
        <form id="question_rating_form" style="display: none">
            {{ question_rating_form }}
        </form>
        <hr>
        <div id="question_comments">
            {% for comment in question.get_comments %}
                <div class="media mb-4">
                    <a href="{% url 'app:user' comment.author.id %}">
                        <img alt="Аватар пользователя" class="d-flex mr-3 rounded-circle"
                             src="{{ comment.author.get_avatar_url }}"
                             style="width: 64px; height: 64px;">
                    </a>
                    <div class="media-body">
                        <h5 class="mt-0">
                            <a href="{% url 'app:user' comment.author.id %}">{{ comment.author }}</a>
                        </h5>
                        {{ comment }}
                    </div>
                </div>
            {% endfor %}
        </div>
        {% if request.user.is_authenticated %}
            <div class="card">
                <form class="form-horizontal" data-avatar-url="{{ request.user.get_avatar_url }}"
                      data-profile-name="{{ request.user }}" data-profile-url="{% url 'app:user' request.user.id %}"
                      onsubmit="commentFormOnSubmit($(this), $('#question_comments')); return false;">
                    {{ comment_to_question_form.question }}
                    <h5 class="card-header">
                        <label for="{{ comment_to_question_form.text.id_for_label }}">Оставить комментарий к
                            вопросу:</label>
                    </h5>
                    <div class="card-body">
                        {{ comment_to_question_form.non_field_errors }}
                        {{ comment_to_question_form.text.errors }}
                        <div class="form-group">
                            {{ comment_to_question_form.text }}
                        </div>
                        <button class="btn btn-primary">Отправить</button>
                    </div>
                </form>
            </div>
            <div class="card mt-3">
                <form class="form-horizontal" method="post">
                    {% csrf_token %}
                    {{ answer_form.question }}
                    <h5 class="card-header">
                        <label for="{{ answer_form.text.id_for_label }}">Ответить на вопрос:</label>
                    </h5>
                    <div class="card-body">
                        {{ answer_form.non_field_errors }}
                        {{ answer_form.text.errors }}
                        <div class="form-group">
                            {{ answer_form.text }}
                        </div>
                        <button class="btn btn-primary">Отправить</button>
                    </div>
                </form>
            </div>
        {% endif %}
        {% if question.answers_count > 0 %}
            <h3 class="mt-4">Ответы ({{ question.answers_count }})</h3>
            <form class="form-horizontal" id="pagination_form">
                {{ pagination_form.as_p }}
            </form>
            {% include 'pagination.html' %}
            {% for answer in pagination %}
                <div class="card mt-4 mb-4" id="answer_{{ answer.id }}">
                    <div class="card-body">
                        <p class="card-text">{{ answer }}</p>
                    </div>
                    <div class="card-footer text-muted">Ответ дан {{ answer.pub_date }} пользователем&nbsp;
                        <a href="{% url 'app:user' answer.author.id %}">{{ answer.author }}</a>
                        <a href="{% url 'app:user' question.author.id %}">
                            <img alt="Аватар пользователя" class="ml-2 rounded-circle avatar32"
                                 src="{{ answer.author.get_avatar_url }}">
                        </a>
                    </div>
                </div>
                <div id="answer_{{ answer.id }}_comments">
                    {% for comment in answer.get_comments %}
                        <div class="media mb-4">
                            <img alt="Аватар пользователя" class="d-flex mr-3 rounded-circle avatar64"
                                 src="{{ comment.author.get_avatar_url }}">
                            <div class="media-body">
                                <h5 class="mt-0">
                                    <a href="{% url 'app:user' comment.author.id %}">{{ comment.author }}</a>
                                </h5>
                                {{ comment }}
                            </div>
                        </div>
                    {% endfor %}
                </div>
                {% if request.user.is_authenticated %}
                    <div class="card">
                        <form class="form-horizontal" data-avatar-url="{{ request.user.get_avatar_url }}"
                              data-profile-name="{{ request.user }}"
                              data-profile-url="{% url 'app:user' request.user.id %}"
                              onsubmit="commentFormOnSubmit($(this), $('#answer_{{ answer.id }}_comments')); return false;">
                            <input name="answer_id" type="hidden" value="{{ answer.id }}">
                            <h5 class="card-header">
                                <label for="{{ comment_to_answer_form.text.id_for_label }}">Оставить комментарий к
                                    ответу:</label>
                            </h5>
                            <div class="card-body">
                                {{ comment_to_answer_form.non_field_errors }}
                                {{ comment_to_answer_form.text.errors }}
                                <div class="form-group">
                                    {{ comment_to_answer_form.text }}
                                </div>
                                <button class="btn btn-primary">Отправить</button>
                            </div>
                        </form>
                    </div>
                {% endif %}
                <hr>
            {% endfor %}
            {% include 'pagination.html' %}
        {% else %}
            <h3 class="mt-4">Ответов нет</h3>
        {% endif %}
    </div>
{% endblock %}
{% block script %}
    <script src="{% static 'pagination.js' %}" type="text/javascript"></script>
    <script src="{% static 'js.cookie.js' %}" type="text/javascript"></script>
    <script src="{% static 'question.js' %}" type="text/javascript"></script>
{% endblock %}

templates/question_pageOld.html
{% extends "inc/base.html" %}
{% load static %}
{% load django_bootstrap5 %}
{% block content %}
    <h2 class="mt-5">Question</h2>
    {% include "inc/question.html" %}
{% endblock %}

{% block side-panel %}
    <h2 class="mt-5">Tags</h2>
{% endblock side-panel %}

templates/questions.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block content %}
    <div class="col-md-8">
        <h1 class="my-3">{% block content_header %}{% endblock %}</h1>
        <form class="form-horizontal" id="pagination_form">
            {{ pagination_form.as_p }}
        </form>
        {% include 'pagination.html' %}
        {% for question in pagination %}
            <div class="card mb-4">
                <div class="card-body">
                    <a href="{% url 'app:question' question.id %}">
                        <h2 class="card-title">{{ question.get_title_short }}</h2>
                    </a>
                    <p class="card-text mb-1">{{ question.get_text_short }}</p>
                    <p class="mt-0 mb-2 text-secondary">
                        {% for question_tag in question.tags.all %}
                            #{{ question_tag }}&nbsp;
                        {% endfor %}
                    </p>
                    <a class="btn btn-primary" href="{% url 'app:question' question.id %}">Перейти &rarr;</a>
                    <i style="float: right">Ответов: <b>{{ question.answers_count }}</b>&nbsp;&nbsp;&nbsp;Рейтинг:
                        {% if question.rating > 0 %}
                            <b class="text-success">+{{ question.rating }}</b>
                        {% elif question.rating < 0 %}
                            <b class="text-danger">{{ question.rating }}</b>
                        {% else %}
                            <b>0</b>
                        {% endif %}
                    </i>
                </div>
                <div class="card-footer text-muted">Задан {{ question.pub_date }} пользователем&nbsp;
                    <a href="{% url 'app:user' question.author.id %}">{{ question.author }}</a>
                    <a href="{% url 'app:user' question.author.id %}">
                        <img alt="Аватар пользователя" class="ml-2 rounded-circle avatar32"
                             src="{{ question.author.get_avatar_url }}">
                    </a>
                </div>
            </div>
        {% endfor %}
        {% include 'pagination.html' %}
    </div>
{% endblock %}
{% block script %}
    <script src="{% static 'pagination.js' %}" type="text/javascript"></script>
{% endblock %}

templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block title %}{{ block.super }}. Регистрация{% endblock %}
{% block content %}
    <div class="col-md-8">
        <h1 class="my-3">Регистрация</h1>
        <form class="form-horizontal" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <div class="form-actions">
                <button class="btn btn-primary" type="submit">Зарегистрироваться</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/tag.html
{% extends 'questions.html' %}
{% block title %}{{ block.super }}. Вопросы по тегу #{{ name }}{% endblock %}
{% block content_header %}Вопросы по тегу #{{ name }}{% endblock %}

templates/top.html
{% extends 'questions.html' %}
{% block title %}{{ block.super }}. Лучшие вопросы{% endblock %}
{% block navbar_top %} active{% endblock %}
{% block content_header %}Лучшие вопросы{% endblock %}

templates/users.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block title %}{{ block.super }}. Пользователи{% endblock %}
{% block navbar_users %} active{% endblock %}
{% block content %}
    <div class="col-md-8">
        <h1 class="my-3">Все пользователи</h1>
        <form class="form-horizontal" id="pagination_form">
            {{ pagination_form.as_p }}
        </form>
        {% include 'pagination.html' %}
        {% for user in pagination %}
            <div>
                <a href="{% url 'app:user' user.id %}">
                    <img alt="Аватар пользователя" class="rounded-circle avatar64" src="{{ user.get_avatar_url }}">
                </a>
                <a href="{% url 'app:user' user.id %}" style="text-align: center;">{{ user.username }}</a>
                <span>&nbsp;Ответов: {{ user.answers_count }}. Вопросов: {{ user.questions_count }}.</span>
            </div>
        {% endfor %}
        {% include 'pagination.html' %}
    </div>
{% endblock %}
{% block script %}
    <script src="{% static 'pagination.js' %}" type="text/javascript"></script>
{% endblock %}